export default [
  {
    id: 1,
    title: 'Malin Kundang Anak Durhaka',
    img: require('../../assets/images/malin_kundang.png'),   // adjust image name/path as needed
    author: 'R. J. Palacio',
    rating: 4.5,
    views: 1280,
    price: 250,
    is_favor: false,
    showall: 'Popular',
    story: 'A folk tale from West Sumatra...',
    color: '#a9745e',
  },
  {
    id: 2,
    title: 'Lalung Kalungan',
    img: require('../../assets/images/lalung_kalungan.png'),
    author: 'K. M. Parini',
    rating: 4.0,
    views: 960,
    price: 150,
    is_favor: true,
    showall: 'Free',
    story: 'Lorem ipsum dolor sit amet...',
    color: '#e8ab3e',
  },
  {
    id: 3,
    title: 'Hikayat Hang Tuah',
    img: require('../../assets/images/hikayat_hang_tuah.png'),
    author: 'Unknown',
    rating: 3.8,
    views: 2100,
    price: 100,
    is_favor: false,
    showall: 'Premium',
    story: 'A legendary Malay warrior...',
    color: '#a9745e35',
  },
];