export const dataUser = [
  {
    id: 1,
    name: "Alya Putri",
    title: "Frontend Developer",
    department: "Engineering",
    email: "alya.putri@example.com",
    image: "https://i.pravatar.cc/150?u=1",
    portofolio: [
      { id: 1, name: "UI Dashboard", code: "FE001", image: "https://i.pravatar.cc/150?u=101" },
      { id: 2, name: "Landing Page", code: "FE002", image: "https://i.pravatar.cc/150?u=102" },
      { id: 3, name: "Portfolio Site", code: "FE003", image: "https://i.pravatar.cc/150?u=103" },
    ],
  },
  {
    id: 2,
    name: "Budi Santoso",
    title: "Backend Developer",
    department: "Engineering",
    email: "budi.santoso@example.com",
    image: "https://i.pravatar.cc/150?u=2",
    portofolio: [
      { id: 1, name: "Auth API", code: "BE001", image: "https://i.pravatar.cc/150?u=201" },
      { id: 2, name: "Payment API", code: "BE002", image: "https://i.pravatar.cc/150?u=202" },
      { id: 3, name: "User Service", code: "BE003", image: "https://i.pravatar.cc/150?u=203" },
    ],
  },
  {
    id: 3,
    name: "Citra Lestari",
    title: "UI/UX Designer",
    department: "Design",
    email: "citra.lestari@example.com",
    image: "https://i.pravatar.cc/150?u=3",
    portofolio: [
      { id: 1, name: "Mobile UI Kit", code: "UX001", image: "https://i.pravatar.cc/150?u=301" },
      { id: 2, name: "Web Redesign", code: "UX002", image: "https://i.pravatar.cc/150?u=302" },
      { id: 3, name: "Prototype App", code: "UX003", image: "https://i.pravatar.cc/150?u=303" },
    ],
  },
  {
    id: 4,
    name: "Dedi Kurniawan",
    title: "DevOps Engineer",
    department: "Infrastructure",
    email: "dedi.kurniawan@example.com",
    image: "https://i.pravatar.cc/150?u=4",
    portofolio: [
      { id: 1, name: "CI/CD Pipeline", code: "DO001", image: "https://i.pravatar.cc/150?u=401" },
      { id: 2, name: "Docker Setup", code: "DO002", image: "https://i.pravatar.cc/150?u=402" },
      { id: 3, name: "Kubernetes Cluster", code: "DO003", image: "https://i.pravatar.cc/150?u=403" },
    ],
  },
  {
    id: 5,
    name: "Eka Saputra",
    title: "QA Engineer",
    department: "Quality Assurance",
    email: "eka.saputra@example.com",
    image: "https://i.pravatar.cc/150?u=5",
    portofolio: [
      { id: 1, name: "Automation Test", code: "QA001", image: "https://i.pravatar.cc/150?u=501" },
      { id: 2, name: "Manual Testing", code: "QA002", image: "https://i.pravatar.cc/150?u=502" },
      { id: 3, name: "Bug Tracker", code: "QA003", image: "https://i.pravatar.cc/150?u=503" },
    ],
  },
  {
    id: 6,
    name: "Fajar Nugroho",
    title: "Mobile Developer",
    department: "Engineering",
    email: "fajar.nugroho@example.com",
    image: "https://i.pravatar.cc/150?u=6",
    portofolio: [
      { id: 1, name: "Android App", code: "MB001", image: "https://i.pravatar.cc/150?u=601" },
      { id: 2, name: "iOS App", code: "MB002", image: "https://i.pravatar.cc/150?u=602" },
      { id: 3, name: "Flutter App", code: "MB003", image: "https://i.pravatar.cc/150?u=603" },
    ],
  },
  {
    id: 7,
    name: "Gina Marlina",
    title: "Data Scientist",
    department: "Data",
    email: "gina.marlina@example.com",
    image: "https://i.pravatar.cc/150?u=7",
    portofolio: [
      { id: 1, name: "ML Model", code: "DS001", image: "https://i.pravatar.cc/150?u=701" },
      { id: 2, name: "Data Pipeline", code: "DS002", image: "https://i.pravatar.cc/150?u=702" },
      { id: 3, name: "Prediction System", code: "DS003", image: "https://i.pravatar.cc/150?u=703" },
    ],
  },
  {
    id: 8,
    name: "Hendra Wijaya",
    title: "System Analyst",
    department: "Business",
    email: "hendra.wijaya@example.com",
    image: "https://i.pravatar.cc/150?u=8",
    portofolio: [
      { id: 1, name: "Requirement Doc", code: "SA001", image: "https://i.pravatar.cc/150?u=801" },
      { id: 2, name: "System Flow", code: "SA002", image: "https://i.pravatar.cc/150?u=802" },
      { id: 3, name: "Use Case", code: "SA003", image: "https://i.pravatar.cc/150?u=803" },
    ],
  },
  {
    id: 9,
    name: "Indah Permata",
    title: "HR Specialist",
    department: "Human Resources",
    email: "indah.permata@example.com",
    image: "https://i.pravatar.cc/150?u=9",
    portofolio: [
      { id: 1, name: "Recruitment Plan", code: "HR001", image: "https://i.pravatar.cc/150?u=901" },
      { id: 2, name: "Training Program", code: "HR002", image: "https://i.pravatar.cc/150?u=902" },
      { id: 3, name: "Employee Survey", code: "HR003", image: "https://i.pravatar.cc/150?u=903" },
    ],
  },
  {
    id: 10,
    name: "Joko Prasetyo",
    title: "Product Manager",
    department: "Management",
    email: "joko.prasetyo@example.com",
    image: "https://i.pravatar.cc/150?u=10",
    portofolio: [
      { id: 1, name: "Product Roadmap", code: "PM001", image: "https://i.pravatar.cc/150?u=1001" },
      { id: 2, name: "Feature Planning", code: "PM002", image: "https://i.pravatar.cc/150?u=1002" },
      { id: 3, name: "Market Analysis", code: "PM003", image: "https://i.pravatar.cc/150?u=1003" },
    ],
  },
  {
    id: 11,
    name: "Kartika Dewi",
    title: "Marketing Specialist",
    department: "Marketing",
    email: "kartika.dewi@example.com",
    image: "https://i.pravatar.cc/150?u=11",
    portofolio: [
      { id: 1, name: "SEO Campaign", code: "MK001", image: "https://i.pravatar.cc/150?u=1101" },
      { id: 2, name: "Social Media Ads", code: "MK002", image: "https://i.pravatar.cc/150?u=1102" },
      { id: 3, name: "Email Campaign", code: "MK003", image: "https://i.pravatar.cc/150?u=1103" },
    ],
  },
  {
    id: 12,
    name: "Lukman Hakim",
    title: "Security Engineer",
    department: "Security",
    email: "lukman.hakim@example.com",
    image: "https://i.pravatar.cc/150?u=12",
    portofolio: [
      { id: 1, name: "Penetration Test", code: "SC001", image: "https://i.pravatar.cc/150?u=1201" },
      { id: 2, name: "Security Audit", code: "SC002", image: "https://i.pravatar.cc/150?u=1202" },
      { id: 3, name: "Vulnerability Scan", code: "SC003", image: "https://i.pravatar.cc/150?u=1203" },
    ],
  },
  {
    id: 13,
    name: "Maya Sari",
    title: "Content Writer",
    department: "Content",
    email: "maya.sari@example.com",
    image: "https://i.pravatar.cc/150?u=13",
    portofolio: [
      { id: 1, name: "Blog Article", code: "CT001", image: "https://i.pravatar.cc/150?u=1301" },
      { id: 2, name: "Copywriting", code: "CT002", image: "https://i.pravatar.cc/150?u=1302" },
      { id: 3, name: "Product Description", code: "CT003", image: "https://i.pravatar.cc/150?u=1303" },
    ],
  },
  {
    id: 14,
    name: "Nanda Prakoso",
    title: "Cloud Engineer",
    department: "Infrastructure",
    email: "nanda.prakoso@example.com",
    image: "https://i.pravatar.cc/150?u=14",
    portofolio: [
      { id: 1, name: "AWS Setup", code: "CL001", image: "https://i.pravatar.cc/150?u=1401" },
      { id: 2, name: "Cloud Migration", code: "CL002", image: "https://i.pravatar.cc/150?u=1402" },
      { id: 3, name: "Serverless App", code: "CL003", image: "https://i.pravatar.cc/150?u=1403" },
    ],
  },
  {
    id: 15,
    name: "Oki Setiawan",
    title: "Game Developer",
    department: "Engineering",
    email: "oki.setiawan@example.com",
    image: "https://i.pravatar.cc/150?u=15",
    portofolio: [
      { id: 1, name: "2D Game", code: "GM001", image: "https://i.pravatar.cc/150?u=1501" },
      { id: 2, name: "3D Game", code: "GM002", image: "https://i.pravatar.cc/150?u=1502" },
      { id: 3, name: "Game Engine", code: "GM003", image: "https://i.pravatar.cc/150?u=1503" },
    ],
  },
  {
    id: 16,
    name: "Putri Anjani",
    title: "AI Engineer",
    department: "Data",
    email: "putri.anjani@example.com",
    image: "https://i.pravatar.cc/150?u=16",
    portofolio: [
      { id: 1, name: "Chatbot AI", code: "AI001", image: "https://i.pravatar.cc/150?u=1601" },
      { id: 2, name: "Image Recognition", code: "AI002", image: "https://i.pravatar.cc/150?u=1602" },
      { id: 3, name: "NLP Model", code: "AI003", image: "https://i.pravatar.cc/150?u=1603" },
    ],
  },
  {
    id: 17,
    name: "Qori Ahmad",
    title: "Support Engineer",
    department: "Support",
    email: "qori.ahmad@example.com",
    image: "https://i.pravatar.cc/150?u=17",
    portofolio: [
      { id: 1, name: "Ticket System", code: "SP001", image: "https://i.pravatar.cc/150?u=1701" },
      { id: 2, name: "Customer Support", code: "SP002", image: "https://i.pravatar.cc/150?u=1702" },
      { id: 3, name: "Knowledge Base", code: "SP003", image: "https://i.pravatar.cc/150?u=1703" },
    ],
  },
  {
    id: 18,
    name: "Rina Kusuma",
    title: "Finance Analyst",
    department: "Finance",
    email: "rina.kusuma@example.com",
    image: "https://i.pravatar.cc/150?u=18",
    portofolio: [
      { id: 1, name: "Budget Planning", code: "FN001", image: "https://i.pravatar.cc/150?u=1801" },
      { id: 2, name: "Financial Report", code: "FN002", image: "https://i.pravatar.cc/150?u=1802" },
      { id: 3, name: "Cost Analysis", code: "FN003", image: "https://i.pravatar.cc/150?u=1803" },
    ],
  },
  {
    id: 19,
    name: "Samsul Bahri",
    title: "Network Engineer",
    department: "Infrastructure",
    email: "samsul.bahri@example.com",
    image: "https://i.pravatar.cc/150?u=19",
    portofolio: [
      { id: 1, name: "LAN Setup", code: "NW001", image: "https://i.pravatar.cc/150?u=1901" },
      { id: 2, name: "VPN Config", code: "NW002", image: "https://i.pravatar.cc/150?u=1902" },
      { id: 3, name: "Firewall Setup", code: "NW003", image: "https://i.pravatar.cc/150?u=1903" },
    ],
  },
  {
    id: 20,
    name: "Tania Oktaviani",
    title: "Business Analyst",
    department: "Business",
    email: "tania.oktaviani@example.com",
    image: "https://i.pravatar.cc/150?u=20",
    portofolio: [
      { id: 1, name: "Business Model", code: "BA001", image: "https://i.pravatar.cc/150?u=2001" },
      { id: 2, name: "Process Mapping", code: "BA002", image: "https://i.pravatar.cc/150?u=2002" },
      { id: 3, name: "Requirement Analysis", code: "BA003", image: "https://i.pravatar.cc/150?u=2003" },
    ],
  },
];